version: '3'

services:
  dave_website:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn docker-dev
    ports:
      - "${WIDGET_HOST_PORT:-4000}:4000"
    volumes:
      - .:/srv/jekyll
